#!/usr/bin/env python

import logging
from pathlib import Path

from lib import bot
from lib.cli import Args
from lib.config import Config


def main() -> None:
    args = Args()
    config = Config()

    LOG_LEVELS = ["DEBUG", "INFO", "INFO", "WARNING", "CRITICAL"]
    assert args.log in LOG_LEVELS, f"Use a valid log level: {LOG_LEVELS}"
    log_file_path = Path("/") / "var" / "log" / "reddit_text_bot.log"
    logging.basicConfig(
        format="[%(asctime)s] %(levelname)s: %(message)s",
        level=args.log,
        # Log to a log file and stderr
        handlers=[logging.FileHandler(log_file_path), logging.StreamHandler()],
    )
    logging.info(f"Logging level: {args.log}")

    bot.run(config, args)


if __name__ == "__main__":
    main()
