#!/usr/bin/env python

from lib import bot
from lib.cli import Args
from lib.config import Config


def main() -> None:
    args = Args()
    config = Config()

    bot.run(config, args)


if __name__ == "__main__":
    main()
