#!/usr/bin/env python

from lib import TextClassifier


def main():
    classifier = TextClassifier()
    print(classifier.predict("2k hours, looking for a squad to raid with"))


if __name__ == "__main__":
    main()
