#!/usr/bin/env python

from lib import score_classifier


def main():
    print(f"{100 * score_classifier()}%")
    # classifier = TextClassifier()
    # print(classifier.predict("2k hours, looking for a squad to raid with"))
    # print(classifier.predict("Difficulty figuring out how to implement Iterator on custom types"))


if __name__ == "__main__":
    main()
